# Generated by Django 5.2.1 on 2025-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_quiz_response_useraccount_rsvped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='temp_password',
            field=models.BooleanField(default=True),
        ),
    ]
