# Generated by Django 5.2.1 on 2025-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='coming',
            field=models.BooleanField(default=True),
        ),
    ]
