# Generated by Django 5.2.1 on 2025-06-03 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('BUNK', 'Bunk Room'), ('TENT', 'Bell Tent'), ('CAMPER', 'Campervan Spot')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('arrival_day', models.CharField(choices=[('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('bringing_food', models.BooleanField(default=False)),
                ('accommodation', models.CharField(choices=[('BUNK', 'Bunk Bed'), ('TENT', 'Bell Tent'), ('CAMPER', 'Campervan')], max_length=10)),
                ('favourite_song', models.CharField(blank=True, max_length=255)),
                ('food_selection', models.CharField(choices=[('VEGGIE', 'Vegetarian'), ('VEGAN', 'Vegan'), ('MEAT', 'Meat'), ('FISH', 'Fish')], max_length=10)),
                ('allergies', models.ManyToManyField(blank=True, to='invitations.allergy')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitations.guest')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='invitations.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
