# Generated by Django 5.2.1 on 2025-06-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='accommodation',
            field=models.CharField(choices=[('BUNK', 'Bunk Bed'), ('TENT', 'Bell Tent'), ('CAMPER', 'Campervan'), ('NOT REQUIRED', 'Not Required')], max_length=14),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='arrival_day',
            field=models.CharField(choices=[('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('rsvped', models.BooleanField(default=False)),
                ('coming', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rsvp',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitations.child'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rsvped', models.BooleanField()),
                ('coming', models.BooleanField()),
                ('partner_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rsvp',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitations.partner'),
        ),
    ]
