# Generated by Django 5.2.1 on 2025-06-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_rsvp_accommodation_alter_rsvp_arrival_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='accommodation',
        ),
    ]
