# Generated by Django 5.2.1 on 2025-07-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_remove_rsvp_accommodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='bringing_food',
            new_name='purchasing_food',
        ),
    ]
