# Generated by Django 5.2.1 on 2025-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_rename_bringing_food_rsvp_purchasing_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
