# Generated by Django 5.2.1 on 2025-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_guestphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='food_selection',
            field=models.CharField(choices=[('VEGGIE', 'Vegetarian'), ('VEGAN', 'Vegan'), ('MEAT', 'Meat'), ('FISH', 'Fish')], default='MEAT', max_length=10),
        ),
    ]
