# Generated by Django 5.2.1 on 2025-08-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='main_screen',
            field=models.BooleanField(default=False),
        ),
    ]
